# Generated by Django 5.1.5 on 2025-02-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_confirmed',
            new_name='is_admin',
        ),
    ]
